### ISSUE TITLE
可否加入play版via浏览器的支持？

### ISSUE THREAD

**Issue by zyh941** [YangguangZhou/Monet-All#1]
当前（1.5版本）似乎只支持酷安版，不支持play版，两者包名有区别，但功能界面上应该差别很小，可否加入支持呢？

**Comment by YangguangZhou** [comment]
对于部分应用，重复添加多个版本的适配只会增加用户选择时的复杂程度，如果您有这样的需求，建议自行使用MT管理器在模块目录下修改包名
