### ISSUE TITLE
安装时无法选取应用

### ISSUE THREAD

**Issue by ironcr** [YangguangZhou/Monet-All#21]
![Screenshot_2024-07-15-15-41-44-01](https://github.com/user-attachments/assets/958b9c7e-0fdf-4319-aff2-35874a99802d)
安装时无法选取每个应用是否安装，机型：一加12 14.0.0.810

**Comment by YangguangZhou** [comment]
beta版本的bug会修复的，请先从tg群中找上一个版本安装
