### ISSUE TITLE
希望适配Magisk应用内的更新功能

### ISSUE THREAD

**Issue by Counta** [YangguangZhou/Monet-All#23]
如题，在module.prop内添加一行
updateJson的键 键指向Json的链接，Json格式如下
```
{
  "versionCode": ,
  "version": "",
  "zipUrl": "zip文件链接",
  "changelog": "更新日志md链接"
}
```

**Comment by YangguangZhou** [comment]
已经适配了 只是链接失效了
![Screenshot_20240724-235036.png](https://github.com/user-attachments/assets/879e933f-b09d-4407-a506-f0c778555082)
我已经替换了链接，现在应该可以自动更新
